name: kernel_build
on: 
  push:
  workflow_dispatch:
jobs:
  kernel:
    runs-on: ubuntu-latest #defines the distro github uses as vm
    steps: #steps of the job
    - uses: actions/checkout@v2 #checkout current branch to see changes and latest commits
    - name: Load ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key:  ${{ runners.os }}
    - name: install dependenices #custom action - name
      #install packages for kernel build like c compiler etc. 
      run: sudo apt install bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils #custom action - content of action - executes shell commands (github actions are run by a small linux VM)
    - name: build kernel
      run: make defconfig && make -j `nproc`
