name: kernel_build

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Install dependencies
      run: sudo apt install -y bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils ccache

    - name: Configure ccache
      run: |
        ccache -M 5G
        export CC="ccache gcc"

    - name: Build kernel
      run: |
        make defconfig
        make -j$(nproc)

    - name: Verify build outputs
      run: ls -R arch/x86/boot

    - name: Upload compiled kernel artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-artifacts
        path: |
          arch/x86/boot/bzImage
          System.map
          vmlinux
