name: kernel_build

on:
  push:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Cache ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Install dependencies
      run: sudo apt install -y bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils ccache

    - name: Configure ccache
      run: |
        ccache -M 5G
        export CC="ccache gcc"

    - name: Build kernel
      run: |
        make defconfig
        make -j$(nproc)

    - name: Verify build outputs
      run: |
        ls -R arch/x86/boot

    - name: Copy kernel files to staging directory
      run: |
        mkdir -p release
        cp arch/x86/boot/bzImage release/vmlinuz
        cp System.map release/System.map
        cp vmlinux release/vmlinux

    - name: Package kernel files
      run: |
        tar -czf kernel-files.tar.gz -C release .

    - name: Upload compiled kernel artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-artifacts
        path: kernel-files.tar.gz

    - name: Create GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: "Kernel Build v${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: kernel-files.tar.gz
        asset_name: kernel-files.tar.gz
        asset_content_type: application/gzip
