name: kernel_test

on:
  push:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-latest  # defines the distro GitHub uses as a VM
    steps:
    - uses: actions/checkout@v2  # checkout current branch to see changes and latest commits

    - name: Cache ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    # Install dependencies (like compilers, etc.)
    - name: Install dependencies
      run: sudo apt install -y bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils ccache
    
    # Build kernel using make
    - name: selftests
      run: |
        make headers
        make -C tools/testing/selftests 
        make -C tools/testing/selftests run_tests
       
    - name: KUnitTest
      run: |
        ./tools/testing/kunit/kunit.py run
    - name: Set execute permissions for the test script
      run: | 
        chmod +x ./tools/testing/crypto/chacha20-s390/run-tests.sh
      
    - name: CryptoTest
      run: |
        ./tools/testing/crypto/chacha20-s390/run-tests.sh
  
