name: kernel_test

on:
  push:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Install dependencies
      run: sudo apt install -y build-essential libncurses5-dev libssl-dev bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils ccache dpkg-dev uml-utilities

    - name: Prepare Kernel Headers
      run: |
        make ARCH=um mrproper
        make ARCH=um headers_install

    - name: Configure KUnit
      run: ./tools/testing/kunit/kunit.py config

    # - name: selftests
    #   run: |
    #     make ARCH=um -C tools/testing/selftests 
    #     make ARCH=um -C tools/testing/selftests run_tests
       
    - name: KUnitTest
      run: |
        ./tools/testing/kunit/kunit.py run

    - name: CryptoTest
      run: |
        chmod +x ./tools/testing/crypto/chacha20-s390/run-tests.sh
        ./tools/testing/crypto/chacha20-s390/run-tests.sh
