name: kernel_test

on:
  push:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Install dependencies
      run: sudo apt install -y build-essential libncurses5-dev libssl-dev bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils ccache dpkg-dev uml-utilities

    - name: Clean and Prepare Build
      run: |
        make ARCH=um mrproper
        ./tools/testing/kunit/kunit.py config

    - name: Build Kernel and Modules
      run: |
        make ARCH=x86_64 olddefconfig
        make ARCH=x86_64 modules_prepare
        make ARCH=x86_64 M=./tools/testing/selftests

    - name: selftests
      run: |
        make ARCH=um -C tools/testing/selftests 
        make ARCH=um -C tools/testing/selftests run_tests

    - name: KUnitTest
      run: |
        ./tools/testing/kunit/kunit.py run

    - name: CryptoTest
      run: |
        sudo chmod +x ./tools/testing/crypto/chacha20-s390/run-tests.sh
        sudo ./tools/testing/crypto/chacha20-s390/run-tests.sh
