name: kernel_test

on:
  push:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-latest  # defines the distro GitHub uses as a VM
    steps:
    - uses: actions/checkout@v2  # checkout current branch to see changes and latest commits

    # Install dependencies (like compilers, etc.)
    - name: Install dependencies
      run: sudo apt install -y bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils ccache

    # Set up ccache (optional: configure cache size if needed)
    - name: Configure ccache
      run: |
        ccache -M 5G  # Set cache size to 5GB
        export CC="ccache gcc"  # Use ccache with gcc

   # - name: selftests
    #  run: |
     #   make headers  # Set default config
      #  make -C tools/testing/selftests 
       # make -C tools/testing/selftests run_tests
       
   # - name: KUnitTest
    #  run: |
     #   ./tools/testing/kunit/kunit.py run

    - name: CryptoTest
      run: |
        ./tools/testing/crypto/chacha20-s390/run-tests.sh
