name: kernel_test

on:
  push:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install -y bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils ccache linux-headers-$(uname -r)

    - name: Configure ccache
      run: |
        ccache -M 5G
        export CC="ccache gcc"

    - name: Set execute permissions for the test script
      run: chmod +x ./tools/testing/crypto/chacha20-s390/run-tests.sh

    - name: Build Kernel Module
      run: |
        cd tools/testing/crypto/chacha20-s390
        make -C /lib/modules/$(uname -r)/build/ M=$(pwd) modules

    - name: Run CryptoTest
      run: ./tools/testing/crypto/chacha20-s390/run-tests.sh

    - name: Clean Build Artifacts
      run: |
        cd tools/testing/crypto/chacha20-s390
        make -C /lib/modules/$(uname -r)/build/ M=$(pwd) clean

   # - name: selftests
    #  run: |
     #   make headers  # Set default config
      #  make -C tools/testing/selftests 
       # make -C tools/testing/selftests run_tests
       
   # - name: KUnitTest
    #  run: |
     #   ./tools/testing/kunit/kunit.py run
   
      
